# -*- coding: utf-8 -*-
"""gradio_frontend-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15mY2a7NdJRyhIQmCxj13kQsLcbQs31dl

# 🎨 Notebook 3: Gradio Frontend
## COMP8420 Assignment 2 - Large Language Models
### Student ID: 48625973

This notebook covers:
- Building an attractive Gradio web interface
- Integrating TinyLlama with the frontend
- Live market data display
- Complete financial advisory chat system
"""

!pip install transformers
!pip install accelerate
!pip install torch
!pip install gradio
!pip install yfinance
!pip install sentencepiece

import torch
import gradio as gr
import yfinance as yf
from transformers import AutoTokenizer, AutoModelForCausalLM
from google.colab import userdata
from huggingface_hub import login

# Login to HuggingFace
token = userdata.get('HF_TOKEN')
login(token=token)

print(f"GPU Available: {torch.cuda.is_available()}")
print(f"Gradio Version: {gr.__version__}")
print("All imports successful!")

# Clear memory first
torch.cuda.empty_cache()

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

print("Loading model...")
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto",
    low_cpu_mem_usage=True
)

model.eval()
print("Model loaded successfully!")
print(f"Memory used: {torch.cuda.memory_allocated()/1e9:.2f} GB")

def generate_response(conversation_history, max_new_tokens=300):
    # Build prompt
    prompt = ""

    for message in conversation_history:
        if message["role"] == "system":
            prompt += f"<|system|>\n{message['content']}</s>\n"
        elif message["role"] == "user":
            prompt += f"<|user|>\n{message['content']}</s>\n"
        elif message["role"] == "assistant":
            prompt += f"<|assistant|>\n{message['content']}</s>\n"

    prompt += "<|assistant|>\n"

    # Tokenize
    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=2048
    ).to("cuda")

    # Generate
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.7,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id,
            repetition_penalty=1.1
        )

    # Decode
    full_response = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    # Extract only assistant response
    if "<|assistant|>" in full_response:
        response = full_response.split("<|assistant|>")[-1].strip()
    else:
        response = full_response.strip()

    return response

print("Generation function ready!")

"""## 1. System Configuration
Setting up the conversation stages and
system prompt for the frontend application.
"""

# Define assistant name here as backup
ASSISTANT_NAME = "FinBot"  # ← Change to your preferred name

QUESTIONS = {
    1: f"Hello! 👋 I am {ASSISTANT_NAME}, your Personal Financial Advisor. What is your full name?",
    2: "Nice to meet you, {name}! How old are you and what is your current occupation?",
    3: "Thank you! What is your monthly income in dollars?",
    4: "Got it! What are your total monthly expenses in dollars?",
    5: "Noted! How much do you currently have in savings?",
    6: "Great! What is your main financial goal? For example: buying a house, retirement, or emergency fund?",
    7: "Almost done! What is your risk tolerance? Choose: Conservative, Moderate, or Aggressive?",
    8: "Thank you {name}! Generating your personalized financial plan now... 🔄"
}

# Global variables
conversation_history = []
current_stage = 1
user_data = {}
device = "cuda" if torch.cuda.is_available() else "cpu"

# Rest of your Cell 11 code continues below...

"""## 2. Live Market Data
Fetching real-time financial market prices
to display in the frontend interface.
"""

def get_market_data():
    """Fetch real market data"""
    tickers = {
        "S&P 500 ETF": "SPY",
        "Gold ETF": "GLD",
        "Bond ETF": "BND",
        "Tech ETF": "QQQ"
    }

    market_info = []
    for name, ticker in tickers.items():
        try:
            stock = yf.Ticker(ticker)
            info = stock.history(period="1d")
            if not info.empty:
                price = info['Close'].iloc[-1]
                market_info.append(f"{name} ({ticker}): ${price:.2f}")
        except:
            market_info.append(f"{name}: Data unavailable")

    return "\n".join(market_info)

# Test it
print("Testing market data...")
print(get_market_data())

"""## 3. Chat Logic
Building the conversation management system
that handles multi-turn dialogue and
tracks user information across stages.
"""

# Global variables
conversation_history = []
current_stage = 1
user_data = {}
device = "cuda" if torch.cuda.is_available() else "cpu"

def get_progress_text():
    global current_stage
    stages = [
        "👋 Greeting",
        "👤 Collecting Name",
        "🎂 Age & Occupation",
        "💵 Monthly Income",
        "💳 Monthly Expenses",
        "💰 Current Savings",
        "🎯 Financial Goals",
        "⚖️ Risk Tolerance",
        "📋 Generating Plan"
    ]
    if current_stage <= len(stages):
        return f"Stage {current_stage}/{len(stages)}: {stages[current_stage-1]}"
    return "✅ Financial plan complete!"

def initialize_conversation():

    global conversation_history, current_stage, user_data


    conversation_history = []
    current_stage = 1
    user_data = {}


    opening = QUESTIONS[1]
    print(f"Opening message: {opening}")
    return opening

def generate_final_recommendation():
    """Use LLM only for final recommendation"""
    try:
        market_data = get_market_data()
    except:
        market_data = "Market data unavailable"

    final_prompt = f"""<|system|>
You are {ASSISTANT_NAME}, an expert financial advisor.
Give clear specific financial advice.</s>
<|user|>
Create a personalized financial plan for this client:

Name: {user_data.get('name', 'Client')}
Age and Job: {user_data.get('age_occupation', 'Not provided')}
Monthly Income: {user_data.get('income', 'Not provided')}
Monthly Expenses: {user_data.get('expenses', 'Not provided')}
Current Savings: {user_data.get('savings', 'Not provided')}
Financial Goal: {user_data.get('goals', 'Not provided')}
Risk Tolerance: {user_data.get('risk', 'Not provided')}

Live Market Data:
{market_data}

Structure your response exactly like this:

💰 FINANCIAL SITUATION SUMMARY
Write 2 sentences about their situation.

🎯 GOAL ANALYSIS
Comment on their specific goals.

📈 INVESTMENT STRATEGY
Give 3 specific recommendations based on risk level.

✅ 5 ACTION STEPS
List 5 practical steps they can take this week.

💡 CLOSING MESSAGE
One encouraging sentence to end.</s>
<|assistant|>
"""
    inputs = tokenizer(
        final_prompt,
        return_tensors="pt",
        truncation=True,
        max_length=1024
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=600,
            temperature=0.7,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id,
            repetition_penalty=1.2
        )

    response = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    if "<|assistant|>" in response:
        response = response.split("<|assistant|>")[-1].strip()

    return response

def chat(user_message, history):
    """Main chat function"""
    global current_stage, user_data

    try:
        if not user_message or user_message.strip() == "":
            return "", history

        user_message = user_message.strip()


        if current_stage == 1:
            user_data['name'] = user_message
        elif current_stage == 2:
            user_data['age_occupation'] = user_message
        elif current_stage == 3:
            user_data['income'] = user_message
        elif current_stage == 4:
            user_data['expenses'] = user_message
        elif current_stage == 5:
            user_data['savings'] = user_message
        elif current_stage == 6:
            user_data['goals'] = user_message
        elif current_stage == 7:
            user_data['risk'] = user_message

        # Get name for personalization
        name = user_data.get('name', 'there')

        # Move to next stage
        current_stage += 1

        if current_stage <= 7:
            # Get next predefined question
            response = QUESTIONS[current_stage].replace(
                '{name}', name
            )
            history.append([user_message, response])

        elif current_stage == 8:
            # Show loading message
            loading = QUESTIONS[8].replace('{name}', name)
            history.append([user_message, loading])

            # Generate LLM recommendation
            recommendation = generate_final_recommendation()
            history.append([
                None,
                f"📋 **Your Personalized Financial Plan**\n\n{recommendation}"
            ])

            current_stage += 1
            return "", history

        else:
            response = f"✅ Thank you {name}! Your financial plan is complete. Click Start New Conversation to begin again."
            history.append([user_message, response])

        return "", history

    except Exception as e:
        print(f"Chat error: {e}")
        history.append([user_message, f"Error: {str(e)}"])
        return "", history

def reset_conversation():
    """Reset and restart"""
    global conversation_history, current_stage, user_data
    conversation_history = []
    current_stage = 1
    user_data = {}

    opening = initialize_conversation()
    return [[None, opening]]

"""## 4. Gradio Interface
Building the attractive dark-themed web
interface with multiple tabs and features.
"""

custom_css = """
/* Main container */
.gradio-container {
    max-width: 1000px !important;
    margin: auto !important;
    background: linear-gradient(135deg, #0f0c29, #302b63, #24243e) !important;
    font-family: 'Segoe UI', sans-serif !important;
}

/* Header styling */
.header-text {
    text-align: center;
    padding: 20px;
    background: linear-gradient(90deg, #00c6ff, #0072ff);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-size: 2.5em !important;
    font-weight: bold !important;
}

/* Chatbot styling */
#chatbot {
    height: 500px !important;
    border-radius: 20px !important;
    border: 1px solid rgba(0, 198, 255, 0.3) !important;
    background: rgba(255,255,255,0.05) !important;
    backdrop-filter: blur(10px) !important;
}

/* Message bubbles */
#chatbot .message {
    border-radius: 15px !important;
    padding: 12px 16px !important;
    margin: 8px !important;
}

/* Input box */
#msg_input textarea {
    background: rgba(255,255,255,0.1) !important;
    border: 2px solid rgba(0, 198, 255, 0.5) !important;
    border-radius: 15px !important;
    color: white !important;
    font-size: 1em !important;
    padding: 12px !important;
}

/* Send button */
#send_btn {
    background: linear-gradient(90deg, #00c6ff, #0072ff) !important;
    border: none !important;
    border-radius: 15px !important;
    color: white !important;
    font-weight: bold !important;
    font-size: 1em !important;
    transition: transform 0.2s !important;
}

#send_btn:hover {
    transform: scale(1.05) !important;
}

/* Start button */
#start_btn {
    background: linear-gradient(90deg, #11998e, #38ef7d) !important;
    border: none !important;
    border-radius: 15px !important;
    color: white !important;
    font-weight: bold !important;
    transition: transform 0.2s !important;
}

#start_btn:hover {
    transform: scale(1.05) !important;
}

/* Refresh button */
#refresh_btn {
    background: linear-gradient(90deg, #f7971e, #ffd200) !important;
    border: none !important;
    border-radius: 15px !important;
    color: white !important;
    font-weight: bold !important;
    transition: transform 0.2s !important;
}

/* Info boxes */
.info-box {
    background: rgba(255,255,255,0.07) !important;
    border: 1px solid rgba(0,198,255,0.2) !important;
    border-radius: 15px !important;
    padding: 15px !important;
    color: white !important;
}

/* Progress bar styling */
.progress-box {
    background: rgba(255,255,255,0.07) !important;
    border: 1px solid rgba(56, 239, 125, 0.3) !important;
    border-radius: 15px !important;
    color: #38ef7d !important;
}

/* Labels */
label {
    color: rgba(255,255,255,0.8) !important;
    font-weight: 600 !important;
}

/* Tabs */
.tab-nav button {
    background: rgba(255,255,255,0.1) !important;
    border-radius: 10px !important;
    color: white !important;
    font-weight: 600 !important;
}

.tab-nav button.selected {
    background: linear-gradient(90deg, #00c6ff, #0072ff) !important;
}
"""

with gr.Blocks(
    css=custom_css,
    title="💰 AI Financial Advisor"
) as demo:

    # ═══════════════════════════════
    # HEADER SECTION
    # ═══════════════════════════════
    gr.Markdown("""
    <div style="text-align:center; padding: 30px 0 10px 0;">
        <div style="font-size:3em;">💰</div>
        <div style="
            font-size:2.2em;
            font-weight:800;
            background: linear-gradient(90deg, #00c6ff, #0072ff, #38ef7d);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 8px;
        ">
            Personal Financial Assistant
        </div>
        <div style="
            color: rgba(255,255,255,0.6);
            font-size:1em;
            letter-spacing: 2px;
        ">
            POWERED BY TINYLLAMA AI
        </div>
        <div style="
            width: 100px;
            height: 3px;
            background: linear-gradient(90deg, #00c6ff, #38ef7d);
            margin: 15px auto;
            border-radius: 10px;
        "></div>
    </div>
    """)

    # ═══════════════════════════════
    # TABS SECTION
    # ═══════════════════════════════
    with gr.Tabs():

        # ── TAB 1: CHAT ──
        with gr.Tab("💬 Financial Chat"):

            # Stats row
            with gr.Row():
                with gr.Column(scale=1):
                    gr.Markdown("""
                    <div style="
                        background: linear-gradient(135deg, #1a1a2e, #16213e);
                        border: 1px solid rgba(0,198,255,0.3);
                        border-radius: 15px;
                        padding: 15px;
                        text-align: center;
                    ">
                        <div style="font-size:2em;">🤖</div>
                        <div style="color:#00c6ff; font-weight:bold; font-size:1.1em;">
                            AI Model
                        </div>
                        <div style="color:white; font-size:0.9em;">
                            TinyLlama 1.1B
                        </div>
                    </div>
                    """)

                with gr.Column(scale=1):
                    gr.Markdown("""
                    <div style="
                        background: linear-gradient(135deg, #1a1a2e, #16213e);
                        border: 1px solid rgba(56,239,125,0.3);
                        border-radius: 15px;
                        padding: 15px;
                        text-align: center;
                    ">
                        <div style="font-size:2em;">📊</div>
                        <div style="color:#38ef7d; font-weight:bold; font-size:1.1em;">
                            Dialogue Stages
                        </div>
                        <div style="color:white; font-size:0.9em;">
                            8 Step Process
                        </div>
                    </div>
                    """)

                with gr.Column(scale=1):
                    gr.Markdown("""
                    <div style="
                        background: linear-gradient(135deg, #1a1a2e, #16213e);
                        border: 1px solid rgba(247,151,30,0.3);
                        border-radius: 15px;
                        padding: 15px;
                        text-align: center;
                    ">
                        <div style="font-size:2em;">📈</div>
                        <div style="color:#ffd200; font-weight:bold; font-size:1.1em;">
                            Live Market Data
                        </div>
                        <div style="color:white; font-size:0.9em;">
                            Real Time Prices
                        </div>
                    </div>
                    """)

                with gr.Column(scale=1):
                    gr.Markdown("""
                    <div style="
                        background: linear-gradient(135deg, #1a1a2e, #16213e);
                        border: 1px solid rgba(255,100,100,0.3);
                        border-radius: 15px;
                        padding: 15px;
                        text-align: center;
                    ">
                        <div style="font-size:2em;">🎯</div>
                        <div style="color:#ff6b6b; font-weight:bold; font-size:1.1em;">
                            Personalized
                        </div>
                        <div style="color:white; font-size:0.9em;">
                            Custom Strategy
                        </div>
                    </div>
                    """)

            # Progress bar
            with gr.Row():
                progress_box = gr.Textbox(
                    label="📊 Conversation Progress",
                    value="👋 Click 'Start New Conversation' to begin!",
                    interactive=False,
                    elem_classes=["progress-box"]
                )

            # Chatbot
            chatbot = gr.Chatbot(
                elem_id="chatbot",
                label="💬 Chat with your Financial Advisor",
                bubble_full_width=False,
                height=450,
                avatar_images=(
                    None,
                    "https://api.dicebear.com/7.x/bottts/svg?seed=financial"
                )
            )

            # Input area
            with gr.Row():
                msg_box = gr.Textbox(
                    placeholder="💬 Type your response here...",
                    label="Your Message",
                    scale=5,
                    elem_id="msg_input"
                )
                send_btn = gr.Button(
                    "Send 📤",
                    variant="primary",
                    scale=1,
                    elem_id="send_btn"
                )

            # Action buttons
            with gr.Row():
                start_btn = gr.Button(
                    "🚀 Start New Conversation",
                    variant="secondary",
                    elem_id="start_btn"
                )
                refresh_btn = gr.Button(
                    "🔄 Refresh Market Data",
                    variant="secondary",
                    elem_id="refresh_btn"
                )

        # ── TAB 2: MARKET DATA ──
        with gr.Tab("📈 Live Market Data"):
            gr.Markdown("""
            <div style="
                color: white;
                font-size: 1.2em;
                font-weight: bold;
                padding: 10px 0;
            ">
                📊 Real-Time Market Overview
            </div>
            """)

            with gr.Row():
                market_box = gr.Textbox(
                    label="📈 Current Market Prices",
                    value=get_market_data(),
                    interactive=False,
                    lines=8,
                    elem_classes=["info-box"]
                )

            with gr.Row():
                gr.Markdown("""
                <div style="
                    background: linear-gradient(135deg, #1a1a2e, #16213e);
                    border: 1px solid rgba(0,198,255,0.2);
                    border-radius: 15px;
                    padding: 20px;
                    color: white;
                ">
                    <h3 style="color:#00c6ff;">📚 Investment Options Guide</h3>
                    <p>🟢 <b>SPY</b> - S&P 500 ETF: Tracks top 500 US companies</p>
                    <p>🟡 <b>GLD</b> - Gold ETF: Safe haven asset</p>
                    <p>🔵 <b>BND</b> - Bond ETF: Lower risk fixed income</p>
                    <p>🟣 <b>QQQ</b> - Tech ETF: Top 100 Nasdaq companies</p>
                </div>
                """)

            refresh_market_btn = gr.Button(
                "🔄 Refresh Market Data",
                variant="primary"
            )

        # ── TAB 3: HOW IT WORKS ──
        with gr.Tab("ℹ️ How It Works"):
            gr.Markdown("""
            <div style="color:white; padding: 20px;">

            <h2 style="color:#00c6ff; text-align:center;">
                🤖 How Your Financial Assistant Works
            </h2>

            <div style="
                background: rgba(255,255,255,0.05);
                border-radius: 15px;
                padding: 20px;
                margin: 10px 0;
                border-left: 4px solid #00c6ff;
            ">
                <h3 style="color:#00c6ff;">Step 1 — 👋 Greeting</h3>
                <p>The AI introduces itself and asks for your name</p>
            </div>

            <div style="
                background: rgba(255,255,255,0.05);
                border-radius: 15px;
                padding: 20px;
                margin: 10px 0;
                border-left: 4px solid #38ef7d;
            ">
                <h3 style="color:#38ef7d;">Step 2 — 👤 Personal Info</h3>
                <p>Collects your age and occupation</p>
            </div>

            <div style="
                background: rgba(255,255,255,0.05);
                border-radius: 15px;
                padding: 20px;
                margin: 10px 0;
                border-left: 4px solid #ffd200;
            ">
                <h3 style="color:#ffd200;">Step 3 — 💵 Financial Situation</h3>
                <p>Asks about your income, expenses and savings</p>
            </div>

            <div style="
                background: rgba(255,255,255,0.05);
                border-radius: 15px;
                padding: 20px;
                margin: 10px 0;
                border-left: 4px solid #ff6b6b;
            ">
                <h3 style="color:#ff6b6b;">Step 4 — 🎯 Goals & Risk</h3>
                <p>Understands your financial goals and risk tolerance</p>
            </div>

            <div style="
                background: rgba(255,255,255,0.05);
                border-radius: 15px;
                padding: 20px;
                margin: 10px 0;
                border-left: 4px solid #a855f7;
            ">
                <h3 style="color:#a855f7;">Step 5 — 📋 AI Recommendation</h3>
                <p>Generates your personalized financial strategy using
                Chain-of-Thought reasoning with live market data</p>
            </div>

            </div>
            """)

    # ═══════════════════════════════
    # FOOTER
    # ═══════════════════════════════
    gr.Markdown("""
    <div style="
        text-align: center;
        padding: 20px;
        color: rgba(255,255,255,0.4);
        font-size: 0.85em;
        border-top: 1px solid rgba(255,255,255,0.1);
        margin-top: 20px;
    ">
        ⚠️ Always consult a qualified financial advisor for real decisions
        <br><br>
        Built with 🤖 TinyLlama • 🐍 Python • 🎨 Gradio
    </div>
    """)

    # ═══════════════════════════════
    # EVENT HANDLERS
    # ═══════════════════════════════
    def handle_send(message, history):
        empty, updated_history = chat(message, history)
        progress = get_progress_text()
        return empty, updated_history, progress

    def handle_start():
        history = reset_conversation()
        progress = get_progress_text()
        return history, progress

    def handle_refresh():
        return get_market_data()

    # Connect events
    send_btn.click(
        handle_send,
        inputs=[msg_box, chatbot],
        outputs=[msg_box, chatbot, progress_box]
    )

    msg_box.submit(
        handle_send,
        inputs=[msg_box, chatbot],
        outputs=[msg_box, chatbot, progress_box]
    )

    start_btn.click(
        handle_start,
        outputs=[chatbot, progress_box]
    )

    refresh_btn.click(
        handle_refresh,
        outputs=[market_box]
    )

    refresh_market_btn.click(
        handle_refresh,
        outputs=[market_box]
    )

"""## 5. Launch Application
Launching the Gradio app with a public
shareable URL for demonstration.
"""

demo.launch(
    share=True,
    debug=True
)

